name: api_showcase
description: "API Showcase - A production-grade Flutter media browser"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.6.4
  dio: ^5.6.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  dart_mappable: ^4.2.2
  auto_route: ^8.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  video_player: ^2.9.2
  cached_network_image: ^3.3.1
  logger: ^2.4.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  dart_mappable_builder: ^4.2.2
  auto_route_generator: ^8.1.0
  mocktail: ^1.0.3
  golden_toolkit: ^0.15.0
  flutter_native_splash: ^2.4.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
