name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  test_analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.16.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info

  build_release:
    if: github.event_name == 'release'
    needs: test_analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.16.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build web
        run: flutter build web --release -t lib/main_prod.dart

      - name: Build APK
        run: flutter build apk --release --target-platform=android-arm,android-arm64,android-x64 -t lib/main_prod.dart --flavor prod

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/web/**
            build/app/outputs/flutter-apk/app-prod-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
